name: streaming

on:
  workflow_dispatch:
  push:

jobs:
  deploy-proxy:
    runs-on: [ self-hosted, kubernetes, bristol ]
    steps:
      - name: checkout
        uses: actions/checkout@v3.1.0

      - name: deploy-nginx
        run: kubectl apply -f nginx.yml